language: python
sudo: false

matrix:
  include:
    - python: 3.7
      dist: focal
      env: TOXENV=py37
    - python: 3.8
      dist: focal
      env: TOXENV=py38
    - python: 3.9
      dist: focal
      env: TOXENV=py39
    - python: 3.10
      dist: focal
      env: TOXENV=py10
    - python: nightly
      dist: focal
      env: TOXENV=py11
  allow_failures:
    - env: TOXENV=py11

before_install:
  - python -m pip install --upgrade pip

# command to install dependencies
install:
  - pip install -r requirements-build.txt

# command to run tests
script:
  # autoformat code following most of the rules in PEP 8
  - black --line-length=99 module/
  # run pytest, codecov, mypy and flake8 with Tox
  - tox -r
